/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface Spreadsheet3s1t {
        "data": string;
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLSpreadsheet3s1tElement extends Components.Spreadsheet3s1t, HTMLStencilElement {
    }
    var HTMLSpreadsheet3s1tElement: {
        prototype: HTMLSpreadsheet3s1tElement;
        new (): HTMLSpreadsheet3s1tElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "spreadsheet-3s1t": HTMLSpreadsheet3s1tElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface Spreadsheet3s1t {
        "data"?: string;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "spreadsheet-3s1t": Spreadsheet3s1t;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "spreadsheet-3s1t": LocalJSX.Spreadsheet3s1t & JSXBase.HTMLAttributes<HTMLSpreadsheet3s1tElement>;
        }
    }
}
